# Generated by Django 5.1.3 on 2025-02-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeteoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('station', models.CharField(max_length=100)),
                ('elevation', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.IntegerField()),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=10)),
                ('temperature_max', models.DecimalField(decimal_places=1, max_digits=10)),
                ('temperature_min', models.DecimalField(decimal_places=1, max_digits=10)),
                ('temperature_trend_hour', models.DecimalField(decimal_places=1, max_digits=10)),
                ('temperature_trend_3hours', models.DecimalField(decimal_places=1, max_digits=10)),
                ('temperature_trend_day', models.DecimalField(decimal_places=1, max_digits=10)),
                ('precipitation', models.DecimalField(decimal_places=1, max_digits=10)),
                ('precipitation_hour', models.DecimalField(decimal_places=1, max_digits=10)),
                ('precipitation_trend_hour', models.DecimalField(decimal_places=1, max_digits=10)),
                ('precipitation_trend_3hours', models.DecimalField(decimal_places=1, max_digits=10)),
                ('precipitation_day', models.DecimalField(decimal_places=1, max_digits=10)),
                ('precipitation_trend_day', models.DecimalField(decimal_places=1, max_digits=10)),
                ('precipitation_month', models.DecimalField(decimal_places=1, max_digits=10)),
                ('pressure', models.DecimalField(decimal_places=1, max_digits=10)),
                ('pressure_trend_hour', models.DecimalField(decimal_places=1, max_digits=10)),
                ('pressure_trend_3hours', models.DecimalField(decimal_places=1, max_digits=10)),
                ('pressure_trend_day', models.DecimalField(decimal_places=1, max_digits=10)),
                ('humidity', models.DecimalField(decimal_places=1, max_digits=10)),
                ('humidity_trend_hour', models.DecimalField(decimal_places=1, max_digits=10)),
                ('humidity_trend_3hours', models.DecimalField(decimal_places=1, max_digits=10)),
                ('humidity_trend_day', models.DecimalField(decimal_places=1, max_digits=10)),
                ('wind_direction', models.CharField(max_length=10)),
                ('wind_speed', models.DecimalField(decimal_places=1, max_digits=10)),
                ('wind_max', models.DecimalField(decimal_places=1, max_digits=10)),
                ('wind_gust', models.DecimalField(decimal_places=1, max_digits=10)),
                ('wind_gust_max', models.DecimalField(decimal_places=1, max_digits=10)),
                ('wind_gust_max_dir', models.CharField(max_length=10)),
                ('wind_chill', models.DecimalField(decimal_places=1, max_digits=10)),
            ],
        ),
    ]
